app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', include('auth_users.urls')),
    path('app/', include('attendance.urls')),
    path('app/student/', include('student.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/urls.py
from django.urls import path
from .views import index, course_added, course_listed, course_attendance,course_registered_students, err404

app_name = 'attendance'

urlpatterns = [
  path('', index, name='home'),
  path('course/add',course_added, name='course_add' ),
  path('course/list',course_listed, name='course_list' ),
  path('course/student/registered/<int:pk>',course_registered_students, name='course_registered_students' ),
  path('course/attendance/<int:pk>',course_attendance, name='course_attendance' ),
  path('page/not/found', err404, name='404')
]

attendance/models.py
import datetime
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image,ImageDraw
from django.contrib.auth.models import User
from helpers.funcs import validateTimer

# Create your models here.




class MarkAttendance(models.Model):
  id = models.AutoField(primary_key=True)
  user = models.ForeignKey(to=User,null=True, related_name='user', on_delete=models.CASCADE)
  date = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return f'{self.user} - {self.date} '
  
  
  
class Attendance(models.Model):
  id = models.AutoField(primary_key=True)
  attendances = models.ManyToManyField(to=MarkAttendance, related_name='attendances', blank=True)
  time_limit = models.CharField(blank=True, max_length=30)
  accessible = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return f'{self.created_at}'
  
  @property
  def isTimeOut(self):
    return validateTimer(self.time_limit)
    
    
    
  @property
  def isOpened(self):
    return self.accessible
  
  @property
  def attendedStudents(self):
    stds = [ std.user for std in self.attendances.all() ]
    return stds
  
  @property
  def isToday(self):
    return self.created_at.date() == datetime.datetime.now().date()


class Course(models.Model):
  name = models.CharField(max_length=100)
  code = models.CharField(max_length=100, unique=True)
  qr_code = models.ImageField(blank=True, upload_to='qr_codes')
  location = models.CharField(max_length=200, blank=True)
  attendance = models.ManyToManyField(to=Attendance, related_name='attendance', blank=True)
  # attendance = models.ForeignKey(to=Attendance, related_name='attendance', on_delete=models.SET_NULL, null=True, blank=True)
  
  def __str__(self):
    return f'{self.name} - {self.code}'
  
  
  @property
  def todayOpenedAttendance(self):
    attendance = list(filter(lambda data: data.isToday == True ,self.attendance.all()))
    return attendance
  
  @property
  def openedCourse(self):
   
    _attendance = [ attendance for attendance in self.attendance.all() if attendance.isTimeOut == False ]
    
    return _attendance[0]
  
  @property
  def all_attendance(self):
    return list(map(lambda data: data, self.attendance.all()))
    
class Student(models.Model):
  id=models.AutoField(primary_key=True)
  level = models.IntegerField(blank=True)
  department = models.CharField(max_length=200, blank=True)
  courses = models.ManyToManyField(to=Course, related_name='courses')
  
  def __str__(self):
    return f'Student {self.id}'
  
  
  @property
  def coursesTaken(self):
    courses = [course.code for course in self.courses.all()]
    return courses
  
class Lecturer(models.Model):
  id=models.AutoField(primary_key=True)
  courses = models.ManyToManyField(to=Course, related_name='lecturer_courses')
  
  def __str__(self):
    return f'Lecture {self.id}'
  
  

  
  
  

  

  

attendance/forms.py
from attendance.models import Course
from django import forms



class CourseForm(forms.ModelForm):
  
  class Meta:
    model = Course
    fields = '__all__'
    

      

attendance/views.py
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse
from django.utils import timezone
from attendance.funcs import setTimeOut
from attendance.models import Attendance, Course
from auth_users.models import Profile
from helpers.funcs import form_errors_decoder
from .forms import CourseForm
from django.shortcuts import get_object_or_404, render, reverse
from django.contrib.auth.models import User

# Create your views here.


def index(request):
  return render(request, 'attendance/index.html')


def course_added(request):
  print('USER: ', request.user)
  context = {}
  if request.method == 'POST':
    form = CourseForm(request.POST, request.FILES)
    if form.is_valid():
      try:
        profile = Profile.objects.get(user=request.user)
        f =  form.save()
        print(f)
        profile.lecturer.courses.add(f)
        profile.save()
      except :
          print('PROFILE DOES NOT EXITS')
     
    context['errs'] = form_errors_decoder(form.errors, 'username')
    context['hasError'] = True if context['errs'] is None else False
  return render(request, 'attendance/course_add.html', context)


def course_listed(request):
  context = {}
  profile = Profile.objects.get(user = request.user)
  context['profile'] = profile
  return render(request, 'attendance/course_list.html', context)


def course_registered_students(request, pk):
  course = None
  context = {}
  
  try:
    course = Course.objects.get(pk=pk)
    context['course'] = course
    student = Profile.objects.filter(student__courses__code = course.code)
    context['students'] = student
    print(student)
  except:
    return HttpResponseRedirect(reverse('attendance:404'))
  
  if request.method == 'POST':
    ID = request.POST['studentID']
    print(ID)
    profile = get_object_or_404(Profile, id=ID)
    profile.student.courses.remove(course)
    profile.save()
    
    # user = User.objects.get(id = ID)
    # user.delete()
    #FIXME: write the delete function 

  
  return render(request, 'attendance/course_registered_students.html', context)


def course_attendance(request, pk):
  course = None
  context = {}
  try:
    course = Course.objects.get(pk=pk)
    context['course'] = course
    # student = course.attendance[0].attendances.all()
    # context['students'] = student
    # print(student)
  except:
    return HttpResponseRedirect(reverse('attendance:404'))
  
  _allAttendance = course.all_attendance
  context['all_attendance'] = _allAttendance
    
  if request.method == 'POST':
    duration = int(request.POST['duration'])
    time = setTimeOut(minutes=duration)
    if len(course.todayOpenedAttendance) > 0 :
      todayAttendance = course.todayOpenedAttendance[0]
      todayAttendance.time_limit = time
      todayAttendance.accessible = True
      todayAttendance.save()
      print('ATTENDANCE UPDATED')
    else:
      attendance = Attendance(time_limit=time, accessible=True)
      attendance.save()
      
      course.attendance.add(attendance)
      course.save()
      
      print('ATTENDANCE CREATED')


  return render(request, 'attendance/course_attendance.html', context)




def err404(request):
  return render(request, 'attendance/404.html')

attendance/templates/attendance/blank.html
{% extends "admin_base.html" %}


{% block Content %}
  
{% endblock Content %}

attendance/templates/attendance/course_add.html
{% extends "admin_base.html" %}
{% load static %}

{% block PageHeader %}
  <h3 class=""><i class="fa fa fa-bars"></i> Course</h3>
  <ol class="list-unstyled d-flex gap-4">
    <li><i class="fa fa-home"></i><a href="index.html">Course</a></li>
    <li><i class="fa fa-bars"></i>Create</li>
    <!-- <li><i class="fa fa-square-o"></i>Pages</li> -->
  </ol>
{% endblock PageHeader %}

{% block Content %}

  <div class="row align-items-center">
    <div class="col-md-6 d-flex align-items-center justify-content-center flex-column">
      <div class="tee-qrcode position-relative" id="qrcode">
        <div class="tee-overlay position-absolute d-flex align-items-center justify-content-center">
          <button id='qrcode-download-btn' class="btn btn-primary fa fa-upload tee-btn" ></button>
        </div>
      </div>
      <div class="py-4">
        <button id='qrcode-generate' class="btn btn-primary fa fa-refresh tee-btn" ></button>
      </div>
    </div>
    <div class="col-md-6">
      {% if errs and errs is not None %}
      <div class="alert alert-danger" role="alert">
        {% for err in errs.errors.values  %}
          <small>{{err}}</small>
        {% endfor %}
      </div>
      {% endif %}
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card shadow p-4 my-2">
          <h3>Create new course</h3>
        </div>
        <div class="form-group">
          <label for="">Course name</label>
          <input type="text" name="name" class="form-control tee-form-control" id="course-name" required>
        </div>
        <div class="form-group">
          <label for="">Course code</label>
          <input type="text" name="code" class="form-control tee-form-control" id="course-code" required>
       
        </div>
        <div class="form-group">
          <label for="">Course File</label>
          <input type="file" name="qr_code" class="form-control tee-form-control" required id='file'>
          <p style="visibility: hidden;">Content: <small id="content"></small></p>
        </div>
        <div class="form-group">
          <button type='submit' class="btn btn-primary tee-btn">
            save
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock Content %}

{% block Script %}
  <script>
    $('document').ready(function(){
      let qr_string = ''
      let qr_str_arr = []
    function createString(){

    }
    function downloadURI(uri, name) {
      var link = document.createElement("a");
      link.download = name;
      link.href = uri;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      delete link;
    };

    function generateQRCode(text){
      let qrcode = new QRCode(document.getElementById("qrcode"),
      {
       text: text,
       width: 400,
       height: 400,
       colorDark : "#000000",
       colorLight : "#ffffff",
       correctLevel : QRCode.CorrectLevel.H
     });

     qrcode.clear()
     qrcode.makeCode(text)
    }



    document.getElementById('qrcode-download-btn').addEventListener('click', () => {
      let dataUrl = document.querySelector('#qrcode').querySelector('img').src;
      downloadURI(dataUrl, `qrcode-${$('#course-code').val().replace(' ', '_')}.png`)
    })

    document.getElementById('qrcode-generate').addEventListener('click', () => {
      const str = `${$('#course-code').val()}`
      generateQRCode(str)
    })

    })
  </script>
  <script src="{% static 'dist/custom/js/qrReader.js' %}"></script>
{% endblock Script %}

attendance/templates/attendance/course_attendance.html
{% extends "admin_base.html" %}


{% block Content %}
  <div class="row">
    <div class="col-md-4">
      <div class="card p-4 shadow tee-attendance__card">
        <div class="card-body">
          <div class="d-flex gap-4 align-items-center">
            <div class="qrcode-box my-4">
              <img src="{{course.qr_code.url}}" alt="">
            </div>
            <div>
              <p class="display-6">Registered Students</p>
              <i class="fa fa-check"></i>
            </div>
          </div>
          <p>{{course.name}}</p>
          <p><b>{{course.code}}</b></p>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <p class="text-center">Click on the button to allow student to take attendance</p>
      <div class="d-flex w-100 h-100 align-items-center justify-content-center flex-column">
        <button id='session-btn' class="btn btn-primary tee-btn my-4">Start session</button>
        <form action="" method="post" class="form-inline invisible" id='session-form'>
          {% csrf_token %}
          <input type="number" placeholder='Enter duration in minutes' class="form-control tee-form-control mb-2 p-4" name='duration'>
          <button type="submit" class="btn btn-outline-primary tee-btn">submit</button>
        </form>
      </div>
    </div>
  </div>
  <div class='py-4'>
    {% for attendance in all_attendance  %}
    <div class="row" style="margin-top:5rem;">
      <div class="col-md-4">
        <div class="card p-4 shadow btn btn-outline-success tee-btn">
          {{attendance.created_at}}
        </div>
      </div>
      <div class="col-md-8 card shadow p-4">
        <table class='table'>
          <thead>
            <tr>
              <th>#</th>
              <th>Index number</th>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            {% for student in attendance.attendances.all %}
              <tr>
                <td></td>
                <td>{{student.user.username}}</td>
                <td>{{student.user.first_name}} {{student.user.last_name}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
  
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock Content %}

{% block Script %}
  <script>
    $(document).ready(function(){
      $('#session-btn').on('click', function(){
        $('#session-form').removeClass('invisible').show(200)
        $(this).hide()
      })

    })
  </script>
{% endblock Script %}

attendance/templates/attendance/course_list.html
{% extends "admin_base.html" %}


{% block Content %}
  <div class="card p-4">
    <p class="display-3">
      Courses Created
    </p>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Course Name</th>
        <th>Course Code</th>
        <!-- <th>Attendance</th> -->
        <th>Registered students</th>
        <th>Mark attendance</th>
      </tr>
    </thead>
    <tbody>
      {% if profile %}
        {% for course in profile.lecturer_courses %}
        <tr>
          <td>#</td>
          <td>{{course.name}}</td>
          <td>{{course.code}}</td>
          <!-- <td>
            <select name="" id="">
           
          </select>
          </td> -->
          <td><a href="{% url 'attendance:course_registered_students' course.id %}" class="btn btn-success tee-btn"><i class="fa fa-eye"></i> students</a></td>
          <td><a href="{% url 'attendance:course_attendance' course.id %}" class="btn btn-outline-primary tee-btn"><i class="fa fa-eye"></i> attendance</a></td>
        </tr>
        {% endfor %}
      {% endif %}
      
    </tbody>
  </table>
{% endblock Content %}

attendance/templates/attendance/course_registered_students.html
{% extends "admin_base.html" %}


{% block Content %}
  <div class="row">
    <div class="col-md-4">
      <div class="card p-4 shadow tee-attendance__card">
        <div class="card-body">
          <div class="d-flex gap-4 align-items-center">
            <div class="qrcode-box my-4">
              <img src="{{course.qr_code.url}}" alt="">
            </div>
          </div>
          <p>{{course.name}}</p>
          <p><b>{{course.code}}</b></p>
        </div>
      </div>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  <div class='py-4'>
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Index Number</th>
          <th>Name</th>
          <th>Level</th>
          <th>Department</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for student in students  %}
          <tr>
            <td></td>
            <td>{{student.user.username}}</td>
            <td>{{student.fullname}}</td>
            <td>{{student.level}}</td>
            <td>{{student.department}}</td>
            <td>
              <form action="" method="post" class="form-inline" id='session-form'>
                {% csrf_token %}
                <input type="checkbox" checked name='studentID' class="invisible" value="{{student.id}}">
                <button type="submit" class="btn btn-outline-danger tee-btn"><i class="fa fa-trash"></i></button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock Content %}

{% block Script %}
  <script>
    $(document).ready(function(){
      $('#session-btn').on('click', function(){
        $('#session-form').removeClass('invisible').show(200)
        $(this).hide()
      })
    })
  </script>
{% endblock Script %}

attendance/templates/attendance/index.html
{% extends "admin_base.html" %}


{% block Content %}
  <div class="text-center">
    <h2 class="display-3">Welcome to Your Dashboard</h2>
  </div>
{% endblock Content %}