app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', include('auth_users.urls')),
    path('app/', include('attendance.urls')),
    path('app/student/', include('student.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from .views import index, incomplete_student, register_class, registered_classes, mark_attendance, mark_attendance_record, find_course, err404

app_name = 'student'

urlpatterns = [
  path('', index, name='home'),
  
  path('incomplete', incomplete_student, name='incomplete_student'),
  
  path('register/classes', registered_classes, name='registered_classes'),
  
  path('register/class/new', register_class, name='register_class'),
  
  path('mark/attendance', mark_attendance, name='mark_attendance'),
  
  path('mark/attendance/course/<int:id>', find_course, name='goto_course'),
  
  path('mark/attendance/record', mark_attendance_record, name='mark_attendance_record'),
  
  path('page/not/found', err404, name='404')
]

student/models.py
from django.db import models

# Create your models here.

student/forms.py
from django import forms




class StudentCompletedForm(forms.Form):
  level = forms.CharField(max_length=3)
  department = forms.CharField(max_length=100)
  

student/views.py
from django.http.response import HttpResponseRedirect
from django.utils import timezone
from student.forms import StudentCompletedForm
from student.decorators import belong_to_group
from django.shortcuts import render, reverse
from django.contrib.auth.models import Group
from auth_users.models import Profile
from attendance.models import Attendance, Course, MarkAttendance, Student
from django.http import JsonResponse
import datetime

from student.funcs import attendance_already_taken, validateTimer
# Create your views here.


def remove_user_group(_user):
  try:
    group = Group.objects.get(name = 'allowed_student')
    group.user_set.remove(_user)
  except:
      print('User does not belong to the group')
      return None
    
def add_user_group(_user):
  try:
    group = Group.objects.get(name = 'allowed_student')
    group.user_set.add(_user)
  except:
      print('User does not belong to the group')
      return None
    
  ##FIXME: create a final statement to create the above group and add student

def setTimeOut(minutes=10):
  print(datetime.datetime.now())
  return datetime.timedelta(minutes=minutes) + datetime.datetime.now()
  



@belong_to_group
def index(request):

  return render(request, 'student/index.html')



def incomplete_student(request):
  print(request.user)
  if request.method == 'POST':
    form = StudentCompletedForm(request.POST)
    
    if form.is_valid():
      student = Student.objects.create(level=form.cleaned_data.get('level'), department=form.cleaned_data.get('department'))
      student.save()
      profile = Profile.objects.get(user=request.user)
      profile.student = student
      profile.save()
   
      add_user_group(request.user)
      
      return HttpResponseRedirect(reverse('student:home'))
    
    print('Errors ', form.errors)
    
  return render(request, 'student/complete_student_form.html')


def registered_classes(request):
  context = {}
  profile = Profile.objects.get(user = request.user)
  context['courses'] = profile.student_courses
  return render(request, 'student/registered_classes.html', context)


def register_class(request):
  
  if request.method == 'POST' and request.is_ajax:
   code = request.POST['code']
   course = Course.objects.filter(code = code)[0]
   profile = Profile.objects.get(user=request.user)
  
   if(code in profile.student.coursesTaken):
      return JsonResponse({
      'status': 'fail',
      })
   
   profile.student.courses.add(course)
   profile.save()
   print(course, profile)
   return JsonResponse({
     'status': 'success',
   })

  return render(request, 'student/register_class.html')


def mark_attendance(request):
  print(request.user)
  context ={}
  
  if request.method == 'POST':
    id = request.POST.get('mark')
    _course = Course.objects.get(id=id)
    _attendance = MarkAttendance(user=request.user)
    _attendance.save()
    _course.attendances.add(_attendance)
    _course.save()
    
    return JsonResponse({'status': 'success'})
    
  profile = Profile.objects.get(user=request.user)
  courses = profile.student.courses.all()
  context['courses'] = courses
  return render(request, 'student/mark_attendance.html', context)


def find_course(request, id):
  course = None
  context = {}
  attendanceToday = None
  
  try:
    course = Course.objects.get(pk=id)
    context['course'] = course
 
  except:
    return HttpResponseRedirect(reverse('student:404'))
  # finally:
  
  try:
    attendanceToday = course.todayOpenedAttendance[0]
  except:
    context['err']  = 'You cannot mark attendance , session has expired'
    return render(request, 'student/find_course_for_attendance.html', context)

  if attendanceToday.isTimeOut:
    context['session_expired'] = True
    return render(request, 'student/find_course_for_attendance.html', context)
  else:
    
    if request.method == 'POST':
      
        if not attendanceToday.isTimeOut and not attendance_already_taken(attendanceToday.attendedStudents, request.user):
          
          att = MarkAttendance(user=request.user)
          att.save()
          attendanceToday.attendances.add(att)
          attendanceToday.save()
          
        else:
          
          if attendance_already_taken(attendanceToday.attendedStudents, request.user):
            context['err']  = 'Attendance already taken'
            
          else:
            context['err']  = 'Attendance access denied'
  
  return render(request, 'student/find_course_for_attendance.html', context)


def mark_attendance_record(request):
  context = {}
  course = Course.objects.filter(attendance__attendances__user=request.user)
  context['courses'] = course
  return render(request, 'student/mark_attendance_record.html', context)


def err404(request):
  return render(request, 'student/404.html')

student/templates/student/complete_student_form.html
{% extends "base.html" %}



{% block Content %}
  
  <div class="incompleted-form" style="z-index: 99999999;">
    <h3 class="display-3 py-4">Complete this section of the form</h3>
    <div class="card">
      <div class="card-body">
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="">Level: </label>
            <input type="text" class="form-control" name='level'>
          </div>
          <div class="form-group">
            <label for="">Deparment: </label>
            <input type="text" class="form-control" name='department'>
          </div>
          <div class="form-group">
            <button class="btn btn-primary">
              submit
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock Content %}

student/templates/student/find_course_for_attendance.html
{% extends "student_base.html" %}


{% block Content %}
<div class="py-4">
  <h2 class="display-3">Complete Attendance</h2>
</div>
{% if err %}
  <div class="alert alert-info">{{err}}</div>
{% endif %}
<div class="row">
  <div class="col-md-5">
    <div class="card p-4 shadow tee-attendance__card">
      <div class="card-body">
        <div class="d-flex gap-4 align-items-center">
          <div class="qrcode-box my-4">
            <img src="{{course.qr_code.url}}" alt="">
          </div>
          <!-- <div>
            <p class="display-6">Attendance in session</p>
            <i class="fa fa-check"></i>
          </div> -->
        </div>
        <p>{{course.name}}</p>
        <p><b>{{course.code}}</b></p>
      </div>
    </div>
  </div>
  {% if session_expired %}
    <div class="col-md-7 d-flex align-items-center justify-content-center" id='session-expired'>
      <p class="display-3">Attendance Session has expired!!</p>
    </div>
  {% else %}
    
  <div class="col-md-7">
    <p class="text-center">Click on the button to allow student to take attendance</p>
    <div class="d-flex w-100 h-100 align-items-center justify-content-center flex-column">
     
      <form action="" method="post" class="form-inline" id='session-form'>
        {% csrf_token %}
        <input type="checkbox" checked class="invisible" name='course_id'>
        {% if err %}
          <button type="submit" class="btn btn-outline-primary tee-btn disabled">Cannot Mark Attendance</button>
        {% endif %}
        {% if not err %}
          <button type="submit" class="btn btn-outline-primary tee-btn">Mark Attendance</button>
        {% endif %}
      </form>
    </div>
  </div>
  {% endif %}
  
</div>
{% endblock Content %}

student/templates/student/index.html
{% extends "student_base.html" %}


{% block Content %}
  <div class="py-4">
    WELCOME TO THE STUDENT DASHBOARD
  </div>
  <div class="row">
    <div class="col-md-4">
      <a href="{% url 'student:registered_classes' %}" class="card btn btn-outline-primary p-4">
        <div class="card-body">
           <h3> View Registered Classes</h3>
        </div>
      </a>
    </div>
    <div class="col-md-4">
      <a href="{% url 'student:mark_attendance' %}" class="card btn btn-outline-warning p-4">
        <div class="card-body">
          <h3>  Take Attendance</h3>
        </div>
      </a>
    </div>
    <div class="col-md-4">
      <a href="{% url 'student:mark_attendance_record' %}" class="card btn btn-outline-danger p-4">
        <div class="card-body">
           <h3> View Attendance Records</h3>
        </div>
      </a>
    </div>
  </div>
{% endblock Content %}

student/templates/student/mark_attendance.html
{% extends "student_base.html" %}


{% block Content %}
<div class="py-4">
  <h2 class="display-3">Mark Attendance</h2>
</div>
<div class="row">
  <div class="col-md-4">
    <div id="tee-alert-success" class="alert alert-success d-none" role="alert">
      <strong>Attendance taken</strong>
    </div>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Course name</th>
      <th>Course code</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for course in courses  %}
      <tr>
        <td></td>
        <td>{{course.name}}</td>
        <td>{{course.code}}</td>
        <td>
            <a href="{% url 'student:goto_course' course.id %}" class="btn btn-success">
              <i class="fa fa-check"></i> mark attendance
            </a>
        </td>
        
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock Content %}

{% block Script %}
<script>

  function alertView(name){
    $(`#tee-alert-${name}`).removeClass('d-none')
    setTimeout(function(){
      $(`#tee-alert-${name}`).addClass('d-none')
    }, 10000)
  }

  $('#mark-attendance').on('submit', function(){
    $.ajax({
      url: '{% url "student:mark_attendance" %}',
      type: 'POST',
      data: $(this).serialize(),
      success: function(res){
        alertView('success')
      },
      error: function(res){

      }
    })
  })
</script>
{% endblock Script %}

student/templates/student/mark_attendance_record.html
{% extends "student_base.html" %}



{% block Content %}
  <div class='py-4'>
    {% if not courses %}
      <h2 class="display-2 text-center">NO records</h2>
    {% endif %}
    {% for course in courses  %}
    <div class="row" style="margin-top:5rem;">
      <div class="col-md-4">
        <div class="card p-4 shadow btn btn-outline-success tee-btn">
          {{course.name}}
        </div>
      </div>
      <div class="col-md-8 card shadow p-4 tee-tiles">
        {% for attendance in course.all_attendance %}
          <p class="text-muted p-4">{{attendance.created_at}}

            <i class="fa fa-check text-success"></i>
          </p>

        {% endfor %}
        <!-- <table class='table'>
          <thead>
            <tr>
              <th>#</th>
              <th>Index number</th>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            {% for student in course.all_attendance %}
              <tr>
                <td></td>
                <td>{{student.username}}</td>
                <td>{{student.user.first_name}} {{student.user.last_name}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table> -->
  
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock Content %}

student/templates/student/register_class.html
{% extends "student_base.html" %}


{% block Content %}
<div class="py-4">
  <h2 class="display-3">Register a new class</h2>
</div>

<div id='tee-alert-success' class="alert alert-success d-none" role="alert">
 <b>Class Registered Successfully</b>
</div>
<div id='tee-alert-error-1' class="alert alert-danger d-none" role="alert">
 <b>You've already registered for this class</b>
</div>
<div id='tee-alert-error-2' class="alert alert-danger d-none" role="alert">
 <b>Registration failed</b>
</div>
<div class="row">
  <div class="col-md-5">
    <div class="tee-qrcode position-relative" id="qrcode">
      <img id="qrcode-img" src="" alt="" >
    </div>
    <div class="col-md-7">
      <i class="fa d-none" id='qrcode-check'
       style="font-size: 5rem;"></i>
    </div>
  </div>
</div>

<p><input type="file"  accept="image/*" name="file" id="file"  onchange="loadFile(event)" class="d-none"></p>
<p id="content"></p>
<p><label for="file" style="cursor: pointer;">Upload Qrcode</label></p>

<form action="" id='class-form'>
  {% csrf_token %}
  <input id="qr" type="text" value="" style="visibility: hidden;">
  <button id="register" type="submit"  class="btn btn-primary p-4 disabled">Register</button>
</form>

<div id='success-toast' class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="d-flex">
    <div class="toast-body">
      Hello, world! This is a toast message.
    </div>
    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>

{% endblock Content %}
{% block Script %}
  <script>
    let load = false;


    function alertView(name){
      $(`#tee-alert-${name}`).removeClass('d-none')
      setTimeout(function(){
        $(`#tee-alert-${name}`).addClass('d-none')
      }, 1000)
    }

    var loadFile = function(event) {
      var image = document.getElementById('qrcode-img');
      image.src = URL.createObjectURL(event.target.files[0]);

  
      if(event.target.files[0].name.slice(-3) === 'png'){
        $('#qrcode-check').removeClass('d-none').removeClass('fa-close').addClass('fa-check')
        $('#register').removeClass('disabled')
      }else{
        $('#qrcode-check').removeClass('d-none').addClass('fa-close')
        $('#register').addClass('disabled')
      }
    };

    $('#class-form').on('submit', function(e){
      e.preventDefault()
      const qrcode_text = document.getElementById('content')
      console.log(qrcode_text.textContent)
      $('#qr').val(qrcode_text.textContent)
      var formData = new FormData()
      formData.append('csrfmiddlewaretoken', $('input[name="csrfmiddlewaretoken"]').val())
      formData.append('code', qrcode_text.textContent.slice(-8))

      console.log(formData, $('input[name="csrfmiddlewaretoken"]').val())
    $.ajax({
        url: '{% url "student:register_class" %}',
        type: 'POST',
        dataType: 'json',
        data: {
          'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
          'code': qrcode_text.textContent
        },
        success: function(res){
          console.log(res)
          if(res.status === 'success'){
            alertView('success')
          }else{
            alertView('error-1')
          }
        },
        error: function(err){
          alertView('error-2')
        },
      })
    })



    $(document).ready(function () {
    })
  </script>
{% endblock Script %}

student/templates/student/registered_classes.html
{% extends "student_base.html" %}


{% block Content %}
<div class="py-4">
  <h2 class="display-3">Registered Classes</h2>
</div>
<div class="d-flex justify-content-end">
  <a href='{% url "student:register_class" %}' type="button" class="btn btn-primary tee-btn" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="Top popover">
   <i class="fa fa-plus"></i> Add Class
  </a>
</div>
<hr>
<h2 class='display-4 py-4'>Enroll classes</h2>
<hr>
<div class="d-flex flex-wrap gap-4 mt-4">
  {% for course in courses %}
  <div class="card p-4 shadow tee-attendance__card">
    <div class="card-body">
      <div class="d-flex gap-4 align-items-center">
        <div class="qrcode-box my-4">
          <img src="{{course.qr_code.url}}" alt="">
        </div>
        <!-- <div>
          <p class="display-6">Attendance in session</p>
          <i class="fa fa-check"></i>
        </div> -->
      </div>
      <p>{{course.name}}</p>
      <p><b>{{course.code}}</b></p>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock Content %}
{% block Script %}
  <script>
    $(document).ready(function () {
      const awn = new AWN()
      awn.modal('<b>Custom modal window message</b>')
    })
  </script>
{% endblock Script %}