app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', include('auth_users.urls')),
    path('app/', include('attendance.urls')),
    path('app/student/', include('student.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/urls.py
from django.urls import path
from .views import index, course_added, course_listed, course_attendance,course_registered_students, err404

app_name = 'attendance'

urlpatterns = [
  path('', index, name='home'),
  path('course/add',course_added, name='course_add' ),
  path('course/list',course_listed, name='course_list' ),
  path('course/student/registered/<int:pk>',course_registered_students, name='course_registered_students' ),
  path('course/attendance/<int:pk>',course_attendance, name='course_attendance' ),
  path('page/not/found', err404, name='404')
]

auth_users/urls.py
from django.urls import path
from .views import index, registerLecturer, registerStudent, logoutUser


app_name = 'auth_users'


urlpatterns = [
  path('', index, name='sign_in'),
  path('register/staff', registerLecturer, name='sign_up_staff'),
  path('register/student', registerStudent, name='sign_up_student'),
  path('logout', logoutUser, name='sign_out'),
]

student/urls.py
from django.urls import path
from .views import index, incomplete_student, register_class, registered_classes, mark_attendance, mark_attendance_record, find_course, err404

app_name = 'student'

urlpatterns = [
  path('', index, name='home'),
  
  path('incomplete', incomplete_student, name='incomplete_student'),
  
  path('register/classes', registered_classes, name='registered_classes'),
  
  path('register/class/new', register_class, name='register_class'),
  
  path('mark/attendance', mark_attendance, name='mark_attendance'),
  
  path('mark/attendance/course/<int:id>', find_course, name='goto_course'),
  
  path('mark/attendance/record', mark_attendance_record, name='mark_attendance_record'),
  
  path('page/not/found', err404, name='404')
]

templates/inc/breadcrum.html
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"><i class="fa fa-laptop"></i> Dashboard</h3>
    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
      <li><i class="fa fa-laptop"></i>Dashboard</li>
    </ol>
  </div>
</div>

templates/inc/custom_aside.html
<aside>
  <div id="sidebar" class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu">
      <li class="active">
        <a class="" href="{% url 'attendance:home' %}">
            <i class="icon_house_alt"></i>
            <span>Dashboard</span>
        </a>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
            <i class="icon_document_alt"></i>
            <span>Course</span>
            <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{% url 'attendance:course_add' %}">Add New Course</a></li>
          <li><a class="" href="{% url 'attendance:course_list' %}">List of courses</a></li>
        </ul>
      </li>
      <!-- <li class="sub-menu">
        <a href="javascript:;" class="">
                      <i class="icon_desktop"></i>
                      <span>UI Fitures</span>
                      <span class="menu-arrow arrow_carrot-right"></span>
                  </a>
        <ul class="sub">
          <li><a class="" href="general.html">Elements</a></li>
          <li><a class="" href="buttons.html">Buttons</a></li>
          <li><a class="" href="grids.html">Grids</a></li>
        </ul>
      </li>
      <li>
        <a class="" href="widgets.html">
                      <i class="icon_genius"></i>
                      <span>Widgets</span>
                  </a>
      </li>
      <li>
        <a class="" href="chart-chartjs.html">
                      <i class="icon_piechart"></i>
                      <span>Charts</span>

                  </a>

      </li>

      <li class="sub-menu">
        <a href="javascript:;" class="">
                      <i class="icon_table"></i>
                      <span>Tables</span>
                      <span class="menu-arrow arrow_carrot-right"></span>
                  </a>
        <ul class="sub">
          <li><a class="" href="basic_table.html">Basic Table</a></li>
        </ul>
      </li>

      <li class="sub-menu">
        <a href="javascript:;" class="">
            <i class="icon_documents_alt"></i>
            <span>Pages</span>
            <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="profile.html">Profile</a></li>
          <li><a class="" href="login.html"><span>Login Page</span></a></li>
          <li><a class="" href="contact.html"><span>Contact Page</span></a></li>
          <li><a class="" href="blank.html">Blank Page</a></li>
          <li><a class="" href="404.html">404 Error</a></li>
        </ul>
      </li> -->

    </ul>
    <!-- sidebar menu end-->
  </div>
</aside>

templates/inc/custom_header.html
{% load static %}
<header class="header dark-bg">
  <div class="toggle-nav">
    <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
  </div>

  <!--logo start-->
  <a href="index.html" class="logo">Attendance <span class="lite">System</span></a>
  <!--logo end-->

  <div class="nav search-row" id="top_menu">
    <!--  search form start -->
    <ul class="nav top-menu">
      <li>
        <form class="navbar-form">
          <input class="form-control" placeholder="Search" type="text">
        </form>
      </li>
    </ul>
    <!--  search form end -->
  </div>

  <div class="top-nav notification-row">
    <!-- notificatoin dropdown start-->
    <ul class="nav pull-right top-menu">
      <!-- alert notification start-->
      <!-- <li id="alert_notificatoin_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">

          <i class="icon-bell-l"></i>
          <span class="badge bg-important">7</span>
      </a>
        <ul class="dropdown-menu extended notification">
          <div class="notify-arrow notify-arrow-blue"></div>
          <li>
            <p class="blue">You have 4 new notifications</p>
          </li>
          
        </ul>
      </li> -->
      <!-- alert notification end-->
      <!-- user login dropdown start-->
      <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="profile-ava">
                <!-- <img alt="" src="{% static 'vendor/img/avatar1_small.jpg' %}"> -->
            </span>
            <span class="username">{{request.user}}</span>
            
        </a>
        <ul class="dropdown-menu extended logout">
          
          <li class="eborder-top">
            <a href="#"><i class="icon_profile"></i> My Profile</a>
          </li>
          <li class="eborder-top">
            <a href="{% url 'auth_users:sign_out' %}"><i class="icon_profile"></i> My Logout</a>
          </li>
        </ul>
      </li>
      <!-- user login dropdown end -->
    </ul>
    <!-- notificatoin dropdown end-->
  </div>
</header>

templates/inc/dashboard_widgets.html
<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="info-box blue-bg">
      <i class="fa fa-cloud-download"></i>
      <div class="count">6.674</div>
      <div class="title">Download</div>
    </div>
    <!--/.info-box-->
  </div>
  <!--/.col-->

  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="info-box brown-bg">
      <i class="fa fa-shopping-cart"></i>
      <div class="count">7.538</div>
      <div class="title">Purchased</div>
    </div>
    <!--/.info-box-->
  </div>
  <!--/.col-->

  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="info-box dark-bg">
      <i class="fa fa-thumbs-o-up"></i>
      <div class="count">4.362</div>
      <div class="title">Order</div>
    </div>
    <!--/.info-box-->
  </div>
  <!--/.col-->

  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="info-box green-bg">
      <i class="fa fa-cubes"></i>
      <div class="count">1.426</div>
      <div class="title">Stock</div>
    </div>
    <!--/.info-box-->
  </div>
  <!--/.col-->

</div>

templates/inc/student_aside.html
<aside>
  <div id="sidebar" class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu">
      <li class="active">
        <a class="" href="{% url 'student:home' %}">
            <i class="icon_house_alt"></i>
            <span>Dashboard</span>
        </a>
      </li>
      <!-- <li class="sub-menu">
        <a href="javascript:;" class="">
            <i class="icon_document_alt"></i>
            <span>Course</span>
            <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="{% url 'attendance:course_add' %}">Add New Course</a></li>
          <li><a class="" href="{% url 'attendance:course_list' %}">List of courses</a></li>
        </ul>
      </li>
      <li class="sub-menu">
        <a href="javascript:;" class="">
                      <i class="icon_desktop"></i>
                      <span>UI Fitures</span>
                      <span class="menu-arrow arrow_carrot-right"></span>
                  </a>
        <ul class="sub">
          <li><a class="" href="general.html">Elements</a></li>
          <li><a class="" href="buttons.html">Buttons</a></li>
          <li><a class="" href="grids.html">Grids</a></li>
        </ul>
      </li>
      <li>
        <a class="" href="widgets.html">
                      <i class="icon_genius"></i>
                      <span>Widgets</span>
                  </a>
      </li>
      <li>
        <a class="" href="chart-chartjs.html">
                      <i class="icon_piechart"></i>
                      <span>Charts</span>

                  </a>

      </li>

      <li class="sub-menu">
        <a href="javascript:;" class="">
                      <i class="icon_table"></i>
                      <span>Tables</span>
                      <span class="menu-arrow arrow_carrot-right"></span>
                  </a>
        <ul class="sub">
          <li><a class="" href="basic_table.html">Basic Table</a></li>
        </ul>
      </li>

      <li class="sub-menu">
        <a href="javascript:;" class="">
            <i class="icon_documents_alt"></i>
            <span>Pages</span>
            <span class="menu-arrow arrow_carrot-right"></span>
        </a>
        <ul class="sub">
          <li><a class="" href="profile.html">Profile</a></li>
          <li><a class="" href="login.html"><span>Login Page</span></a></li>
          <li><a class="" href="contact.html"><span>Contact Page</span></a></li>
          <li><a class="" href="blank.html">Blank Page</a></li>
          <li><a class="" href="404.html">404 Error</a></li>
        </ul>
      </li> -->

    </ul>
    <!-- sidebar menu end-->
  </div>
</aside>

templates/inc/student_header.html
{% load static %}
<header class="header dark-bg">
  <div class="toggle-nav">
    <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
  </div>

  <!--logo start-->
  <a href="index.html" class="logo">Attendance <span class="lite">System</span></a>
  <!--logo end-->

  <div class="nav search-row" id="top_menu">
    <!--  search form start -->
    <ul class="nav top-menu">
      <li>
        <form class="navbar-form">
          <input class="form-control" placeholder="Search" type="text">
        </form>
      </li>
    </ul>
    <!--  search form end -->
  </div>

  <div class="top-nav notification-row">
    <!-- notificatoin dropdown start-->
    <ul class="nav pull-right top-menu">
      <!-- alert notification start-->
      <!-- <li id="alert_notificatoin_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">

          <i class="icon-bell-l"></i>
          <span class="badge bg-important">7</span>
      </a>
        <ul class="dropdown-menu extended notification">
          <div class="notify-arrow notify-arrow-blue"></div>
          <li>
            <p class="blue">You have 4 new notifications</p>
          </li>
        </ul>
      </li> -->
      <!-- alert notification end-->
      <!-- user login dropdown start-->
      <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="profile-ava">
                <!-- <img alt="" src="{% static 'vendor/img/avatar1_small.jpg' %}"> -->
            </span>
            <span class="username">{{request.user}}</span>
            
        </a>
        <ul class="dropdown-menu extended logout">
          
          <li class="eborder-top">
            <a href="#"><i class="icon_profile"></i> My Profile</a>
          </li>
          <li class="eborder-top">
            <a href="{% url 'auth_users:sign_out' %}"><i class="icon_profile"></i> My Logout</a>
          </li>
        </ul>
      </li>
      <!-- user login dropdown end -->
    </ul>
    <!-- notificatoin dropdown end-->
  </div>
</header>